# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dca < Formula
  desc "Discord CLI for Agents - Feature-complete Discord automation"
  homepage "https://github.com/ulfschnabel/dca"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.1.0/dca_0.1.0_darwin_amd64.tar.gz"
      sha256 "a7c04291c62fe0f069c6f3bb3ba78363feae4fd41d1117a9abd4d3e261020f03"

      def install
        bin.install "dca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.1.0/dca_0.1.0_darwin_arm64.tar.gz"
      sha256 "1b9a9a06f7a2f4a2e462be5a8b548ec172c70b8209614403a7975debc5c85555"

      def install
        bin.install "dca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.1.0/dca_0.1.0_linux_amd64.tar.gz"
      sha256 "c941e1aa03e54b8c3730df22a0dc153fb3907b50fc25ffb57e8b027a516082a2"
      def install
        bin.install "dca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.1.0/dca_0.1.0_linux_arm64.tar.gz"
      sha256 "dcb601e9fec41ca25f1b1b8ddace8c3b892d38ed4a3f2dff7b3375795ecb25bd"
      def install
        bin.install "dca"
      end
    end
  end
end
