# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GagentCli < Formula
  desc "Google Workspace automation CLI for AI agents"
  homepage "https://github.com/ulfschnabel/gagent-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.1/gagent-cli_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "c03587230d2f299a10f05b4b9f95ac36f0571f32046853463cc8e42e9fba425c"

      def install
        bin.install "gagent-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.1/gagent-cli_0.4.1_Darwin_arm64.tar.gz"
      sha256 "00dfbce7af1f4329d71191fcbb1c2fdafba55cbeab0b440417e9e80bdc48bf3c"

      def install
        bin.install "gagent-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.1/gagent-cli_0.4.1_Linux_x86_64.tar.gz"
      sha256 "7a30eb87528817fdff524c6b29a9932508ae705ffa3fb46f5b37b2ad2ceb6cb5"
      def install
        bin.install "gagent-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.1/gagent-cli_0.4.1_Linux_arm64.tar.gz"
      sha256 "18bdd8277eff17bee5efd4e0424085ff6c846a585d1c61f6f2ee1876ff1b19a4"
      def install
        bin.install "gagent-cli"
      end
    end
  end

  test do
    system "#{bin}/gagent-cli", "--version"
  end
end
