# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dca < Formula
  desc "Discord CLI for Agents - Feature-complete Discord automation"
  homepage "https://github.com/ulfschnabel/dca"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.2.0/dca_0.2.0_darwin_amd64.tar.gz"
      sha256 "e281bcc7186407e0cfe7cfaca3a30c9c7b3e323c8765a11dd42d82c9e2b853be"

      def install
        bin.install "dca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.2.0/dca_0.2.0_darwin_arm64.tar.gz"
      sha256 "ce23d909da1ec23e0b1c062606c09b878c427c29ae48a835ba25a5801834427f"

      def install
        bin.install "dca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.2.0/dca_0.2.0_linux_amd64.tar.gz"
      sha256 "44260d35d158f42de410f2de1e6213c847ac2825a1d8f7d6d84b9badbafd63b3"
      def install
        bin.install "dca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/dca/releases/download/v0.2.0/dca_0.2.0_linux_arm64.tar.gz"
      sha256 "726878817608aec408ac3bce1a82d7d64fbad54df8e9798e2b351142c1f5b1f5"
      def install
        bin.install "dca"
      end
    end
  end
end
