# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GagentCli < Formula
  desc "Google Workspace automation CLI for AI agents"
  homepage "https://github.com/ulfschnabel/gagent-cli"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.3/gagent-cli_0.4.3_Darwin_x86_64.tar.gz"
      sha256 "93080cfdef300fb42ebd6a2bdaacc27af639458ab70fa2499a233dc457c1bd66"

      def install
        bin.install "gagent-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.3/gagent-cli_0.4.3_Darwin_arm64.tar.gz"
      sha256 "5630f986e64bde9311b0988ff26799526f592f35d4af0d0fb89a6d7c7a16974e"

      def install
        bin.install "gagent-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.3/gagent-cli_0.4.3_Linux_x86_64.tar.gz"
      sha256 "ec70099844e53c103165a7f0a92026586e8cb5614f2f672a1662988518cbd831"
      def install
        bin.install "gagent-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ulfschnabel/gagent-cli/releases/download/v0.4.3/gagent-cli_0.4.3_Linux_arm64.tar.gz"
      sha256 "f6654ed2e065cd953ad29b3c8e6ef2c213bd5fe94bf7ef97dd487876c14e3141"
      def install
        bin.install "gagent-cli"
      end
    end
  end

  test do
    system "#{bin}/gagent-cli", "--version"
  end
end
